// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdvKQr5DeOeGMgBnjowgvd9HmGkIErVzs',
    appId: '1:731297882434:web:7a960d0456756c8cd0e8db',
    messagingSenderId: '731297882434',
    projectId: 'techveda-a8e41',
    authDomain: 'techveda-a8e41.firebaseapp.com',
    storageBucket: 'techveda-a8e41.firebasestorage.app',
    measurementId: 'G-MXTNV0FFKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGzAj6TcQNczj2bDciul-6dCHDMG3kTr4',
    appId: '1:731297882434:android:91a9e8ef8ccbf8d1d0e8db',
    messagingSenderId: '731297882434',
    projectId: 'techveda-a8e41',
    storageBucket: 'techveda-a8e41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2l8bq349UpIluJBxPb5dtHmKdGNr5HhI',
    appId: '1:731297882434:ios:888d7baef17f89ced0e8db',
    messagingSenderId: '731297882434',
    projectId: 'techveda-a8e41',
    storageBucket: 'techveda-a8e41.firebasestorage.app',
    iosBundleId: 'com.example.techVeda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2l8bq349UpIluJBxPb5dtHmKdGNr5HhI',
    appId: '1:731297882434:ios:888d7baef17f89ced0e8db',
    messagingSenderId: '731297882434',
    projectId: 'techveda-a8e41',
    storageBucket: 'techveda-a8e41.firebasestorage.app',
    iosBundleId: 'com.example.techVeda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdvKQr5DeOeGMgBnjowgvd9HmGkIErVzs',
    appId: '1:731297882434:web:50c6ce95434dc8a4d0e8db',
    messagingSenderId: '731297882434',
    projectId: 'techveda-a8e41',
    authDomain: 'techveda-a8e41.firebaseapp.com',
    storageBucket: 'techveda-a8e41.firebasestorage.app',
    measurementId: 'G-T3D49P2NLC',
  );
}
